### ISSUE TITLE
初始化耗时问题

### ISSUE THREAD

**Issue by xiaxinqing** [jadepeakpoet/ARouter#10]
新增以下代码 并没有减缓耗时问题
使用ARouter 项目 的application 到第一个Activity的启动耗时：450毫秒左右
2023-05-18 11:39:23.268 13858-13858/com.spreadit.spreaditapp.uat D/===time==: MyApplication1——#methodA#Cost:0
2023-05-18 11:39:23.722 13858-13858/com.spreadit.spreaditapp.uat D/===time==: StartActivity——#methodA#Cost:454

未使用ARouter项目  的application 到第一个Activity的启动耗时：
2023-05-18 11:44:09.331 16312-16312/com.spreadit.spreaditapp D/===time==: MyApplication——#methodA#Cost:0
2023-05-18 11:44:09.528 16312-16312/com.spreadit.spreaditapp D/===time==: StartActivity——#methodA#Cost:259

中间几乎未做任何其他耗时操作（已经排查过）

请大佬指教。

加入了一下代码

###
使用 Gradle 插件实现路由表的自动加载 (可选)

apply plugin: 'com.alibaba.arouter'

buildscript {
    repositories {
        maven { url 'https://www.jitpack.io' }
    }

    dependencies {
        classpath "com.github.jadepeakpoet.ARouter:arouter-register:1.0.2"
    }
}
可选使用，通过 ARouter 提供的注册插件进行路由表的自动加载(power by [AutoRegister](https://github.com/luckybilly/AutoRegister))， 默认通过扫描 dex 的方式 进行加载通过 gradle 插件进行自动注册可以缩短初始化时间解决应用加固导致无法直接访问 dex 文件，初始化失败的问题，需要注意的是，该插件必须搭配 api 1.3.0 以上版本使用！

###

**Comment by xiaxinqing** [comment]
@jadepeakpoet 引入ARouter的项目，经过反复测试对比：要比去掉的耗时多200毫秒多一点。请大佬指点一下

**Comment by xiaxinqing** [comment]
解决了，原来不止文档说的这一些配置，组件化项目需要在所有包含 ：
#
apply plugin: 'com.android.application' 的地方
#
都要加上
#
 apply plugin: 'com.alibaba.arouter'
#
 至此 将扫描时间 转换成了编译时间。
感谢大佬的改造开源

**Comment by jadepeakpoet** [comment]
@xiaxinqing 感谢使用和支持，从开源中来，到开源中去，对本fork项目的star和认可，就是对我最大的鼓励，这地方的确是个小坑，这个ARouter的原始文档的确没有提到那么细，就是多个applicationd的情况，不过这种需要配置classpath的插件，扫描整个应用的，本就是要在application模块中配置才会生效(比如每个application模块，都要配置com.android.application插件，每个library模块，都要配置com.android.library)，你组件化有多个application模块，其实就相当于有多个应用，只配置A模块，就只对A应用有效，对B模块(application)而言，根本就没有引入这个插件，这个是插件自身的规则，不是ARouter的定制，很多人开源或者使用的组件化框架，可能都会疏忽这一点，只不过大部分情况下，只会对开发期间有影响，上线时还是用的正式的application模块，所以生产包没问题，你提到的这个问题，我可以在文档里补充一下，防止后来人继续踩坑。
