### ISSUE TITLE
感谢作者适配，升级agp7+后，viewmodels识别不出来，搞了两天发现是ARouter的问题。真坑

### ISSUE THREAD

**Issue by zs1973** [jadepeakpoet/ARouter#11]
感谢作者适配，升级agp7+后，viewmodels识别不出来，搞了两天发现是ARouter的问题。真坑

**Comment by jadepeakpoet** [comment]
@zs1973 多谢支持，原有官方的ARouter的确很久没更新了，在新的AGP上，要么使用有问题，要么编译不通过，自己的升级项目的时候，ARouter业是一个很大的阻碍，看到issue区，很多开发都碰到了类似的问题，所以萌生出了fork改造并回馈开源的想法，很高兴这个项目能给大家带来帮助。

**Comment by zs1973** [comment]
> 
准备用货拉拉的按个TheRouter试试，看看怎么样

**Comment by jadepeakpoet** [comment]
> 
@zs1973 

货拉拉TheRouter有自动将ARouter转换过去的插件，可以一试，那个功能也会更多一些，我主要是做一些升级适配和bug的维护，基本不怎么加新功能（时间精力不太够）。

另外，我还是想确认一个问题，使用我适配过的ARouter插件，viewmodels现在是不是可以正常找到，我这边配合hilt使用起来目前看起来都是正常的。

**Comment by zs1973** [comment]
是的 viewmodels是可以正常找到的，之前找不到是因为老版本arouter里面的appcompat库版本太老了是support的，你这个androidX是正常的。



---原始邮件---
发件人: "Yufeng ***@***.***&gt;
发送时间: 2023年5月19日(周五) 中午11:07
收件人: ***@***.***&gt;;
抄送: "Tom ***@***.******@***.***&gt;;
主题: Re: [jadepeakpoet/ARouter] 感谢作者适配，升级agp7+后，viewmodels识别不出来，搞了两天发现是ARouter的问题。真坑 (Issue #11)




   
@zs1973
 
货拉拉TheRouter有自动将ARouter转换过去的插件，可以一试，那个功能也会更多一些，我主要是做一些升级适配和bug的维护，基本不怎么加新功能（时间精力不太够）。
 
另外，我还是想确认一个问题，使用我适配过的ARouter插件，viewmodels现在是不是可以正常找到，我这边配合hilt使用起来目前看起来都是正常的。
