### ISSUE TITLE
AGP兼容问题

### ISSUE THREAD

**Issue by louis2610** [jadepeakpoet/ARouter#2]
你这个fork支持AGP 7.3.1和Gradle 7.4以上吗

**Comment by jadepeakpoet** [comment]
> 

支持的，正常7.3.X系列应该都支持，AGP7.3.1+Gradle7.4的组合，我自己也用过，然后对于这种基于注解的库，一般使用的时候能编译通过，相关用到的功能点能正常调用，也就是支持了。
