### ISSUE TITLE
请问支持KSP吗？

### ISSUE THREAD

**Issue by jiqianwen** [jadepeakpoet/ARouter#3]
## Look at here

- → Did you read the doc carefully
- → Did you add annotation above target activity
- → Did you add annotation processor dependence
- → **Receive only bugs and suggestions**

## 提 issue 前请看

- → 你是否已经熟读 [README](https://github.com/alibaba/ARouter/blob/master/README.md) ？
- → 你是否在每一个包含页面 or 服务的模块中依赖了 compiler sdk
- → **这里不是答疑的地方，仅接受 bug 和建议，答疑请去答疑群**

**Comment by jadepeakpoet** [comment]
相对于原库，主要解决的是gradle升级之后ARouter不可用的问题，暂时没做其他方向的优化，目前使用的应该还是和原库一样的kapt，KSP后续会考虑做优化支持

以下是本库目前所做相关优化
1.迁移到androidx，对于本库可关闭jetifier(android.enableJetifier=false)或不做配置
2.适配到AGP7.3.0，解决其中的兼容性bug
3.升级依赖的第三方库
4.在jitpack发布本库

**Comment by jiqianwen** [comment]
> 相对于原库，主要解决的是gradle升级之后ARouter不可用的问题，暂时没做其他方向的优化，目前使用的应该还是和原库一样的kapt，KSP后续会考虑做优化支持
> 
> 以下是本库目前所做相关优化 1.迁移到androidx，对于本库可关闭jetifier(android.enableJetifier=false)或不做配置 2.适配到AGP7.3.0，解决其中的兼容性bug 3.升级依赖的第三方库 4.在jitpack发布本库

好的，了解，辛苦了~

**Comment by JailedBird** [comment]
> 

仓库1:https://github.com/JailedBird/ARouter/tree/feature-ksp-jitpack , fork arouter添加ksp支持
仓库2:https://github.com/JailedBird/ArouterKspCompiler, PR没人合并, 就在仓库1的基础上打成的独立插件

大佬, 有兴趣在项目中添加对KSP的实现么?

**Comment by jadepeakpoet** [comment]
官方的不用想了，KPI项目没人维护了。。。（以前在阿里内部使用一些类似的库很多时候都找不到人维护。。。）
最近事情比较多，没怎么看github，等后面有空了研究一下
最初fork本库的主要目的也是保持ARouter在高版本AGP上的可用性，对ksp没有太多诉求，原计划是相等升级AGP8.0的时候，在依旧支持kapt的基础上(有些使用者的老项目可能是java写的，然后ksp本身也可能存在一些兼容性问题)，增加ksp支持（毕竟ksp只是快了一些，而且主要是针对kotlin，但是原库只升级AGP则可能编译不通过。。。）。

另外，关于ksp在Arouter上的使用，不知道你那里是否有实测的kapt和ksp编译速度的对比呢

**Comment by JailedBird** [comment]
![image](https://user-images.githubusercontent.com/113177053/225239919-afbbec87-8a0b-4e43-a6d7-d54968b7e85a.png)

KSP的最大优势就是在于当模块中不存在任何KAPT的时候, 可以彻底移除kaptGenerateStub这个过程[这个过程一般占20%左右的编译时间吧], 从而提升编译时间;
但是排除kaptGenerateStub过程的耗时,单纯比较kapt和ksp感觉没啥具体的意义, 又能差几秒呢? 所以没做这方面比较;
目前的趋势: Glide\Room\Moshi.....都已经支持KSP(参考[这里](http://kotlin.liying-cn.net/docs/reference_zh/ksp/ksp-overview.html#%E6%94%AF%E6%8C%81%E7%9A%84%E5%BA%93)), Dagger\HILT正在支持中, 升级的意义在于不要让ARouter的存在影响大家对KAPT的移除😁
当然迁移不是必要的, 并不影响使用😁
