### ISSUE TITLE
升级后出现Compiler An exception is encountered, [null]。之前用阿里的库是没问题的，大牛帮忙看下

### ISSUE THREAD

**Issue by asking1233** [jadepeakpoet/ARouter#4]
ARouter::Compiler An exception is encountered, [null]
      at com.alibaba.android.arouter.compiler.processor.AutowiredProcessor.generateHelper(AutowiredProcessor.java:87)
      at com.alibaba.android.arouter.compiler.processor.AutowiredProcessor.process(AutowiredProcessor.java:70)
      at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
      at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:197)

**Comment by jadepeakpoet** [comment]
1.迁移到androidx，对于本库可关闭jetifier(android.enableJetifier=false)或不做配置
2.适配到AGP7.3.0，解决其中的兼容性bug
3.升级依赖的第三方库
4.在jitpack发布本库

你好，以上是本库文档里提供的相对于原库的一个变更，我排查了一下代码，推测你的项目还是基于android support库的，没有秦迁移到androidx（或者说你是混用的），本库已经迁移到了androidx。

    private void generateHelper() throws IOException, IllegalAccessException {
        TypeElement type_ISyringe = elementUtils.getTypeElement(ISYRINGE);
        TypeElement type_JsonService = elementUtils.getTypeElement(JSON_SERVICE);
        TypeMirror iProvider = elementUtils.getTypeElement(Consts.IPROVIDER).asType();
        TypeMirror activityTm = elementUtils.getTypeElement(Consts.ACTIVITY).asType();
        TypeMirror fragmentTm = elementUtils.getTypeElement(Consts.FRAGMENT).asType();
        TypeMirror fragmentTmV4 = elementUtils.getTypeElement(Consts.FRAGMENT_V4).asType();//问题出在这一行，87行

    public static final String FRAGMENT_V4 = "androidx.fragment.app.Fragment"; // 已经迁移到androidx

以下是从android support迁移到androidx的教程，androidx已经普及好几年啦，快来升级吧

Android Support迁移AndroidX
https://www.jianshu.com/p/ffae21f7f143
