### ISSUE TITLE
NestHost requires ASM7

### ISSUE THREAD

**Issue by licoba** [jadepeakpoet/ARouter#5]
## 是否有碰到这个问题？
![image](https://user-images.githubusercontent.com/19327381/228764244-b4b2dbb3-10bd-4b23-a684-e2cad6a4eb84.png)

**Comment by jadepeakpoet** [comment]
这个问题没碰到过呢，是AGP的bug，提供下你的gradle和AGP版本吧（7.0.1及以上应该没问题），然后编译项目执行gradle task的时候使用java11

TypedefRemover uses ASM5 and is incompatible with JDK 11 sources that require ASM7 
https://issuetracker.google.com/issues/195449882

我这里使用以下组合没问题，你可以试下。
gradle-7.4
AGP7.3.0, 7.3.1

gradle-7.5.1
7.4.2

**Comment by licoba** [comment]
我暂时没用这个库了，版本忘记了不好意思哈~

**Comment by blundell** [comment]
Perhaps you where using the optional auto-register plugin:

<img width="1247" alt="image" src="https://github.com/jadepeakpoet/ARouter/assets/655860/29cf2afe-0f5d-4f2a-84b2-66831bf76b43">

That only has support for ASM6 (https://github.com/luckybilly/AutoRegister), but this fork updated it (https://github.com/ooftf/AutoRegister) and then ASM 9 support was added here: https://github.com/ooftf/AutoRegister/pull/2
