### ISSUE TITLE
升级AGP8.0编译报错了

### ISSUE THREAD

**Issue by Louiswang86** [jadepeakpoet/ARouter#7]
具体报错：An exception occurred applying plugin request [id: 'com.alibaba.arouter']
> Failed to apply plugin 'com.alibaba.arouter'.
   > API 'android.registerTransform' is removed.
![image](https://user-images.githubusercontent.com/19605506/232960667-801a5728-ac61-41a6-9bec-1d55ad03b271.png)

**Comment by jadepeakpoet** [comment]
AGP8暂时不支持哦（Transform被干掉了），我现在已经在做迁移工作了，搞了一部分，下一个版本会支持AGP8.0(顺利的话，大概这周就会发布新版本)。

**Comment by jadepeakpoet** [comment]
> 具体报错：An exception occurred applying plugin request [id: 'com.alibaba.arouter']
> 
> > Failed to apply plugin 'com.alibaba.arouter'.
> > API 'android.registerTransform' is removed.
> > ![image](https://user-images.githubusercontent.com/19605506/232960667-801a5728-ac61-41a6-9bec-1d55ad03b271.png)

AGP8.0已于昨日适配，使用1.0.3版本即可
